/* automatically generated by rust-bindgen 0.64.0 */
use crate::execution_engine::LLVMGenericValueRef;
use crate::prelude::LLVMTypeRef;

#[repr(C)]
#[derive(Debug, Copy, Clone, Default)]
pub struct MiriPointer {
    pub addr: ::std::os::raw::c_ulonglong,
    pub alloc_id: ::std::os::raw::c_ulonglong,
    pub tag: ::std::os::raw::c_ulonglong,
    pub offset: ::std::os::raw::c_ulonglong,
}

pub type MiriInterpCxOpaque = ::std::os::raw::c_void;

pub type MiriAllocationHook = ::std::option::Option<
    unsafe extern "C-unwind" fn(arg1: *mut MiriInterpCxOpaque, arg2: ::libc::size_t) -> MiriPointer,
>;
pub type MiriFreeHook = ::std::option::Option<
    unsafe extern "C-unwind" fn(arg1: *mut MiriInterpCxOpaque, arg2: MiriPointer),
>;
pub type MiriLoadStoreHook = ::std::option::Option<
    unsafe extern "C-unwind" fn(
        arg1: *mut MiriInterpCxOpaque,
        arg2: LLVMGenericValueRef,
        arg3: MiriPointer,
        arg4: LLVMTypeRef,
        arg5: ::libc::size_t,
    ),
>;
pub type MiriCallbackHook = ::std::option::Option<
    unsafe extern "C-unwind" fn(
        arg1: *mut MiriInterpCxOpaque,
        arg2: LLVMGenericValueRef,
        arg3: ::libc::size_t,
        arg4: *const ::std::os::raw::c_char,
        arg5: ::libc::size_t,
    ),
>;
